PIP

In [ ]:
# ! wget -P ~/ https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# ! chmod +x ~/Miniconda3-latest-Linux-x86_64.sh
# ! ~/Miniconda3-latest-Linux-x86_64.sh -b
# ! export PATH=~/miniconda3/bin:$PATH
# ! conda init & conda# ! wget -P ~/ https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# ! chmod +x ~/Miniconda3-latest-Linux-x86_64.sh
# ! ~/Miniconda3-latest-Linux-x86_64.sh -b
# ! export PATH=~/miniconda3/bin:$PATH
# ! conda init & conda config --set auto_activate_base false
# # close and start a new session
# ! conda activate base
# ! conda install cudatoolkit=11.0 -y
# ! pip install sentence-transformers   transformers datasets peft accelerate bitsandbytes 
# ! conda install -c pytorch -c nvidia faiss-gpu=1.8.0
# !pip install faiss-gpu config --set auto_activate_base false
# # close and start a new session
# ! conda activate base
# ! conda install cudatoolkit=11.0 -y
# ! pip install sentence-transformers   transformers datasets peft accelerate bitsandbytes faiss-cpu faiss-gpu

Imports

In [1]:
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments, AdamW
from peft import prepare_model_for_kbit_training, LoraConfig, get_peft_model, PeftModel, PeftConfig
from sentence_transformers import SentenceTransformer, util
import faiss
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, TensorDataset

if torch.backends.mps.is_available():  # Check for Apple Silicon GPU availability (requires PyTorch 1.12 or later)
    device = torch.device("mps")
elif torch.cuda.is_available():  # Check for NVIDIA GPU availability
    device = torch.device("cuda")
else:
    device = torch.device("cpu")  # Fall back to CPU

print(f"Using device: {device}")

Using device: cuda


Dataset

In [2]:
dataset = load_dataset('ms_marco', 'v2.1')
print(dataset)

DatasetDict({
    validation: Dataset({
        features: ['answers', 'passages', 'query', 'query_id', 'query_type', 'wellFormedAnswers'],
        num_rows: 101093
    })
    train: Dataset({
        features: ['answers', 'passages', 'query', 'query_id', 'query_type', 'wellFormedAnswers'],
        num_rows: 808731
    })
    test: Dataset({
        features: ['answers', 'passages', 'query', 'query_id', 'query_type', 'wellFormedAnswers'],
        num_rows: 101092
    })
})


In [3]:
train_dataset = dataset['train'].select(range(1000))
train_dataset = train_dataset.filter(lambda example: example['wellFormedAnswers'] != [] and example['wellFormedAnswers'] != "")
print(len(train_dataset))

134


Unique Documents List

In [4]:
unique_passages = set()
for row in train_dataset:
    unique_passages.update(row['passages']['passage_text'])
print(len(unique_passages))
documents = list(unique_passages)

1333


HUgginface login

In [5]:
from huggingface_hub import login
login(token="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")

Token has not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid (permission: write).
Your token has been saved to /root/.cache/huggingface/token
Login successful


Load SentenceTransformer

In [6]:
# SentenceTransformer("all-MiniLM-L6-v2")
SentenceTranformer = SentenceTransformer(
    'sentence-transformers/msmarco-bert-base-dot-v5',
    device = device,
    )

Test SentenceTransformer

In [7]:
query_embedding = SentenceTranformer.encode('How big is London')
print("embedding length: ", len(query_embedding))
document_embedding = SentenceTranformer.encode(
    [
        'London has 9,787,426 inhabitants at the 2011 census',
        'London is known for its finacial district',
    ])

print("Similarity:", util.dot_score(query_embedding, document_embedding))


embedding length:  768
Similarity: tensor([[166.5561, 159.5406]])


Generate Embeddings from all documents

In [8]:
# Encode documents
document_embeddings = SentenceTranformer.encode(
    documents, 
    show_progress_bar=True, 
    device = device,
    batch_size=100
)

Batches:   0%|          | 0/14 [00:00<?, ?it/s]

Create Faiss Index from all documents

In [9]:
faiss.normalize_L2(document_embeddings)

In [10]:
index = faiss.IndexFlatIP(document_embeddings.shape[1])  # L2 distance
index.add(document_embeddings)

Store Faiss index to storage and read from storage

In [11]:
faiss.write_index(index, "index_docs.index")
# index = faiss.read_index("index_docs.index")

Test Faiss Index

In [ ]:
# res = faiss.StandardGpuResources() 
# index_gpu = faiss.index_cpu_to_gpu(res, 0, index)

In [12]:
test_query = ["This is a query test.", "This is a query donut."]
test_query_embedding = SentenceTranformer.encode(test_query)
# print("test_query_embedding: ", test_query_embedding)
faiss.normalize_L2(test_query_embedding)

k = 5  # Number of similar documents to retrieve
D, I = index.search(test_query_embedding, k)
print("D: ", D)
print("I: ", I)
D_tensor = torch.tensor(D)
D_softmax = F.softmax(D_tensor, dim=1)  # Apply softmax along the rows
D_softmax_np = D_softmax.numpy()
print(D_softmax)
print("Most similar documents to the query:")
for i, idx in enumerate(I[0]):
    print(f"Rank {i+1}: {documents[idx]}")
for i, idx in enumerate(I[1]):
    print(f"Rank {i+1}: {documents[idx]}")

D:  [[0.90023875 0.89977723 0.89780843 0.8967315  0.8966974 ]
 [0.8674655  0.867303   0.86647964 0.8658711  0.8655468 ]]
I:  [[ 299  556  759 1116  977]
 [1223  699  101  792  393]]
tensor([[0.2004, 0.2003, 0.1999, 0.1997, 0.1997],
        [0.2002, 0.2002, 0.2000, 0.1999, 0.1998]])
Most similar documents to the query:
Rank 1: A vitamin B12 test measures the amount of vitamin B12 in the blood. The normal values listed here-called a reference range-are just a guide. These ranges vary from lab to lab, and your lab may have a different range for what's normal.
Rank 2: Results. A vitamin B12 test measures the amount of vitamin B12 in the blood. The normal values listed here-called a reference range-are just a guide. These ranges vary from lab to lab, and your lab may have a different range for what's normal.
Rank 3: It could be argued that, in a powerlifting context, the deadlift is a true measure of strength due to its lack of emphasis on various performance aids (suits etc). It also emplo

Configure LoRA and sentenceTranformer of query

In [13]:
from sentence_transformers import SentenceTransformer
queryTranformer = SentenceTransformer(
    'sentence-transformers/msmarco-bert-base-dot-v5',
    device = device,
)

Define sentenceTransformer in training mode 

Define LoRA and EncoderDecoder GPT2 

In [14]:
from transformers import GPT2Model, GPT2Tokenizer
# Generator = GPT2Model.from_pretrained('gpt2')
# tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
generator = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")
tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2", padding_side='left', pad_token = "<|pad|>")
# 50257 - output seq
print(generator)
print(tokenizer)

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)
GPT2TokenizerFast(name_or_path='openai-community/gpt2', vocab_size=50257, model_max_length=1024, is_fast=True, p

Define GPT2 in training mode

Define custom lost function???


In [31]:
K = 3
batch_size = 2

Create training object combined????

In [16]:
# tokenizer.add_special_tokens({'pad_token': '[PAD]'})

# encodings_dict = tokenizer('<|startoftext|>'+ txt + '<|endoftext|>', truncation=True, max_length=max_length, padding="max_length")
# print(train_dataset['query'])
max_seq_len = 768

inputs = tokenizer(
    train_dataset['query'], 
    max_length=max_seq_len, 
    padding='max_length', 
    truncation=True,
    return_tensors='pt'
)
# print(type(inputs))
print(type(inputs['input_ids']), inputs['input_ids'].shape)
print(type(inputs['attention_mask']), inputs['attention_mask'].shape)


flattened_answers = [sublist[0] for sublist in train_dataset['wellFormedAnswers']]
# Prepend <sos> token (this will handle the right shit)

targets = tokenizer(
    flattened_answers, 
    max_length=max_seq_len, 
    padding='max_length', 
    truncation=True,
    return_tensors='pt'
)

print(type(targets['input_ids']), targets['input_ids'].shape)

<class 'torch.Tensor'> torch.Size([134, 768])
<class 'torch.Tensor'> torch.Size([134, 768])
<class 'torch.Tensor'> torch.Size([134, 768])


In [17]:
trainingDataset = TensorDataset(inputs['input_ids'], inputs['attention_mask'], targets['input_ids'], targets['attention_mask'])
trainingDataloader = DataLoader(trainingDataset, batch_size, shuffle=False,)  

In [18]:
def custom_loss(logits, labels):
    loss = torch.mean((logits - labels) ** 2)  # For example, mean squared error
    return loss

In [65]:
class SuperModel(torch.nn.Module):
    def __init__(self, generator, queryTranformer, index, documents):
        super().__init__()
        self.generator = generator
        self.queryTranformer = queryTranformer
        self.documents = documents
        self.index = index

    def forward(self, batch_inputs_ids, attention_masks, label_ids, labels_attention_mask, K, max_seq_len):
        
        queries = tokenizer.batch_decode(
            batch_inputs_ids,
            skip_special_tokens = True
        )

        queries_embedding = self.queryTranformer.encode(queries)  # Pass appropriate inputs

        D, I = index.search(queries_embedding, K)
        D_tensor = torch.tensor(D)
        D_softmax = F.softmax(D_tensor, dim=-1) 

        prompts = []

        for ind in range(len(I)):
            for i, idx in enumerate(I[ind]):
                prompt = self.documents[idx] + " " + queries[ind] #No look ahead mask wanted here 
                prompts.append(prompt)

        tokinized_prompts_ids = tokenizer(
            prompts, 
            max_length=max_seq_len, 
            padding='max_length', 
            truncation=True,
            return_tensors='pt'
        )

        # look ahead mask - one token at a time 
        
        input_ids = tokinized_prompts_ids["input_ids"].view(len(queries), K, -1)
        attention_mask = tokinized_prompts_ids["attention_mask"].view(len(queries), K, -1)

        generator.resize_token_embeddings(len(tokenizer))
        # input_ids = 
        generatorOutput = self.generator(
            input_ids = input_ids,
            attention_mask = attention_mask
        )

        softmaxed_logits = F.softmax(generatorOutput.logits, dim=-1) 
        D_softmax_unsqueezed = D_softmax.view(D_softmax.size(0), D_softmax.size(1), 1, 1)
        weighted_logits = softmaxed_logits * D_softmax_unsqueezed
        marginalised = torch.mean(weighted_logits, dim=1)
        
        shifted_tokinesed_input = None
        return marginalised, shifted_tokinesed_input

In [66]:
model = SuperModel(
    generator = generator , 
    queryTranformer = queryTranformer , 
    index = index , 
    documents = documents ,
)

In [67]:
optimizer = AdamW(model.parameters(), lr=5e-5)

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:521: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [68]:
i = 0
for batch in trainingDataloader:  # Size: Batch_size x Seq_length
    optimizer.zero_grad()
    i+=1
    
    outputs = model(
        batch_inputs_ids = batch[0], 
        attention_masks= batch[1], 
        label_ids = batch[2],
        labels_attention_mask = batch[3],
        K = K,
        max_seq_len=max_seq_len
    )


    break
    
    # loss = outputs.loss
    # loss.backward()
    # optimizer.step()

    # print(f"Loss: {loss.item()}")

torch.Size([2, 768, 50258])


In [ ]:
logits = torch.ones([1, 2, 3, 4])
print("logits: \n",logits)

softmaxed_logits = F.softmax(logits, dim=-1) 

print("logits soft max: \n",softmaxed_logits)

probability = custom_tensor = torch.tensor([[0.5, 2]])
print(logits.shape, probability.shape)

tensor2_expanded = probability.view(probability.size(0), probability.size(1), 1, 1)
test = softmaxed_logits * tensor2_expanded

print(test.shape)
print(test)

mean_tensor = torch.mean(test, dim=1)
print(mean_tensor.shape)
print(mean_tensor)


logits: 
 tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
logits soft max: 
 tensor([[[[0.2500, 0.2500, 0.2500, 0.2500],
          [0.2500, 0.2500, 0.2500, 0.2500],
          [0.2500, 0.2500, 0.2500, 0.2500]],

         [[0.2500, 0.2500, 0.2500, 0.2500],
          [0.2500, 0.2500, 0.2500, 0.2500],
          [0.2500, 0.2500, 0.2500, 0.2500]]]])
torch.Size([1, 2, 3, 4]) torch.Size([1, 2])
torch.Size([1, 2, 3, 4])
tensor([[[[0.1250, 0.1250, 0.1250, 0.1250],
          [0.1250, 0.1250, 0.1250, 0.1250],
          [0.1250, 0.1250, 0.1250, 0.1250]],

         [[0.5000, 0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000, 0.5000]]]])
torch.Size([1, 3, 4])
tensor([[[0.3125, 0.3125, 0.3125, 0.3125],
         [0.3125, 0.3125, 0.3125, 0.3125],
         [0.3125, 0.3125, 0.3125, 0.3125]]])


In [ ]:
# class CustomTrainer(Trainer):
#     def compute_loss(self, model, inputs, return_outputs=False):
#         labels = inputs.pop("labels")
#         outputs = CustomModel(**inputs)
#         logits = outputs.logits
#         loss = custom_loss(logits, labels)
#         return (loss, outputs) if return_outputs else loss

In [ ]:
# # Define your model, tokenizer, and training arguments
# model = ...  # Define your model here
# tokenizer = ...  # Define your tokenizer here
# training_args = TrainingArguments(
#     ...
# )  # Define your training arguments here

In [ ]:
# trainer = CustomTrainer(
#     modelok=model,
#     args=training_args,
#     train_dataset=train_dataset,
#     eval_dataset=eval_dataset,
#     tokenizer=tenizer,
# )

Run Training

In [ ]:
# trainer.train()

Inference test data

Store model

Build API 

Pack to Docker Container

Publish

In [ ]:

# Select and Prepare a Pre-trained Seq2Seq Model
# Generate the Response
# Evaluation and Iteration
